apiVersion: v1
kind: ConfigMap
metadata:
  name: {{- .Values.app.name }}
  {{ if .Values.configmap }}
data: 
  {{- range $key,  $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | quote}}
  {{- end}}