apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kube-stack-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: tml0289@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - http01:
        ingress:
          class: nginx 