{{- range .Values.app }}
{{- if .ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  namespace: {{ .name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName:  nginx
  rules:
    - host: {{ .ingress.host }}
      http:
        paths:
          - path: {{ .ingress.path }}
            pathType: {{ .ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .service.port }}
{{- end }}
{{- end }}