{{- range .Values.app }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  type: {{ .service.type | default "ClusterIP" }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.targetPort | default "http" }} 
      protocol: {{ .service.protocol | default "TCP"}} 
  selector:
    app: {{.name }}
{{- end}}